admin_recovery_code: UCB-RECOVERY-2026
custom_config: --oem 3 --psm 7 -c tessedit_char_whitelist=ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789
database_url: sqlite:///parking.db
forbidden_vehicle_types:
- camping_car
- poids_lourd
- bus
forbidden_yolo_classes:
- truck
- bus
secret_key: ucb_parking_secret_key_2026
smtp:
  from_address: system.parking.ucbukavu@gmail.com
  host: smtp.gmail.com
  password: ksrouzqyhllsytjl
  port: 587
  user: system.parking.ucbukavu@gmail.com
tesseract_cmd: C:\Program Files\Tesseract-OCR\tesseract.exe
